export const FamousList = [
  {
    name: "luna",
    isVerified: true,
    imageUrl: "/images/logo192.png",
    twitterName: "@itš_me_luna",
    description:
      "music composer, Drummer in Indian film industry / Cricketer music composer, Drummer in Indian film industry / Cricketer music composer, Drummer in Indian film industry / Cricketer music composer, Drummer in Indian film industry / Cricketer",
    followers: 1900000,
    following: 354,
    friendsFollowing: ["name_is_Girish", "Itachi"],
  },
  {
    name: "Naruto",
    isVerified: false,
    imageUrl: "/images/logo192.png",
    twitterName: "@Uzumaki_Naruto",
    description: "music composer, Drummer",
    followers: 1900000,
    following: 354,
  },
  {
    name: "Itachi_Uchiha",
    isVerified: true,
    imageUrl: "/images/logo192.png",
    twitterName: "@UchihaITACHI",
    description: "music composer, Drummer in Indian film industry / Cricketer",
    followers: 1900000,
    following: 354,
  },
  {
    name: "Light",
    isVerified: true,
    imageUrl: "/images/logo192.png",
    twitterName: "@KiraLIGHT",
    description: "music composer, Drummer in Indian film industry / Cricketer",
    followers: 1900000,
    following: 354,
  },
  {
    name: "Peachy",
    isVerified: true,
    imageUrl: "/images/logo192.png",
    twitterName: "@Peachy",
    description: "music composer, Drummer in Indian film industry / Cricketer",
    followers: 1900000,
    following: 354,
  },
];
